/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
      extend: {
          fontFamily: {
              'sans': ['Inter', 'system-ui', 'sans-serif'],
              'outfit': ['Outfit', 'sans-serif'],
          },
          colors: {
              'primary': {
                  DEFAULT: 'rgb(var(--primary-rgb) / <alpha-value>)',
                  foreground: 'rgb(var(--primary-fg-rgb) / <alpha-value>)',
                  50: 'rgb(var(--primary-rgb) / <alpha-value>)',
                  100: 'rgb(var(--primary-rgb) / <alpha-value>)',
                  200: 'rgb(var(--primary-rgb) / <alpha-value>)',
                  300: 'rgb(var(--primary-rgb) / <alpha-value>)',
                  400: 'rgb(var(--primary-rgb) / <alpha-value>)',
                  500: 'rgb(var(--primary-rgb) / <alpha-value>)',
                  600: 'rgb(var(--primary-rgb) / <alpha-value>)',
                  700: 'rgb(var(--primary-rgb) / <alpha-value>)',
                  800: 'rgb(var(--primary-rgb) / <alpha-value>)',
                  900: 'rgb(var(--primary-rgb) / <alpha-value>)',
                  950: 'rgb(var(--primary-rgb) / <alpha-value>)',
              },
              'secondary': {
                  DEFAULT: 'rgb(var(--secondary-rgb) / <alpha-value>)',
                  foreground: 'rgb(var(--secondary-fg-rgb) / <alpha-value>)',
                  50: 'rgb(var(--secondary-rgb) / 0.05)',
                  100: 'rgb(var(--secondary-rgb) / 0.1)',
                  200: 'rgb(var(--secondary-rgb) / 0.2)',
                  300: 'rgb(var(--secondary-rgb) / 0.3)',
                  400: 'rgb(var(--secondary-rgb) / 0.4)',
                  500: 'rgb(var(--secondary-rgb) / 0.5)',
                  800: 'rgb(var(--secondary-rgb) / 0.8)',
                  900: 'rgb(var(--secondary-rgb) / 0.9)',
              },
              'accent': {
                  DEFAULT: 'rgb(var(--accent-rgb) / <alpha-value>)',
                  foreground: 'rgb(var(--accent-fg-rgb) / <alpha-value>)',
                  50: 'rgb(var(--accent-rgb) / 0.05)',
                  100: 'rgb(var(--accent-rgb) / 0.1)',
                  200: 'rgb(var(--accent-rgb) / 0.2)',
                  300: 'rgb(var(--accent-rgb) / 0.3)',
                  400: 'rgb(var(--accent-rgb) / 0.8)',
                  500: 'rgb(var(--accent-rgb) / 1)',
                  600: 'rgb(var(--accent-rgb) / 1)',
                  900: 'rgb(var(--accent-rgb) / 1)',
              },
              'surface': {
                  50: '#f8fafc',
                  100: '#f1f5f9',
                  800: '#1f2937',
                  900: '#111827',
                  950: '#0a0f1a',
              },
              pitch: {
                  50: 'rgb(var(--pitch-50-rgb) / <alpha-value>)',
                  100: 'rgb(var(--pitch-100-rgb) / <alpha-value>)',
                  500: 'rgb(var(--pitch-500-rgb) / <alpha-value>)',
                  600: 'rgb(var(--pitch-600-rgb) / <alpha-value>)',
                  700: 'rgb(var(--pitch-700-rgb) / <alpha-value>)',
                  800: 'rgb(var(--pitch-800-rgb) / <alpha-value>)',
                  900: 'rgb(var(--pitch-900-rgb) / <alpha-value>)',
              },
          },
          animation: {
              'float': 'float 6s ease-in-out infinite',
              'glow': 'glow 2s ease-in-out infinite alternate',
              'slide-up': 'slideUp 0.5s ease-out',
              'slide-in': 'slideIn 0.3s ease-out',
              'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
              'fade-in': 'fadeIn 0.4s ease forwards',
          },
      }
  },
  plugins: [],
}